### ISSUE TITLE
formal identifier grammar doesn't match prose

### ISSUE THREAD

**Issue by CAD97** [kdl-org/kdl#255] opened 2022-02-02 20:49 UTC
[The prose](https://github.com/kdl-org/kdl/blob/main/SPEC.md#non-identifier-characters) says that

> Non-identifier characters
>
> The following characters cannot be used anywhere in a bare Identifier:
>
> - Any codepoint with hexadecimal value 0x20 or below.
> - Any codepoint with hexadecimal value higher than 0x10FFFF.
> - Any of `\/(){}<>;[]=,"`

The formal grammar says that

```
identifier-char := unicode - linespace - [\/(){}<>;[]=,"]
linespace := newline | ws | single-line-comment

newline := See Table (All line-break white_space)
unicode-space := See Table (All White_Space unicode characters which are not `newline`)
```

This means that the formal grammar excludes 0x09, 0x0A, 0x0C, 0x0D, and 0x20, but allows the other codepoints < 0x20.

The prose also doesn't specify that all whitespace is non-identifier characters, though this is clearly implied, and doesn't matter as much as it does in the grammar formalization.

**Comment by zkat** [comment] 2022-02-02 21:27
Happy to take a patch for this!

**Comment by marrus-sh** [comment] 2022-09-05 06:33
(this is a duplicate of #191)

**Comment by zkat** [comment] 2023-12-13 05:54
This should be fixed in the kdl-v2 branch

**Closed by zkat** 2023-12-13 05:54 UTC
Labels: bug, documentation, help wanted, good first issue
